{% set name = "bmtk" %}
{% set version= "0.0.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_rev: "v{{ version }}"
  git_url: https://github.com/AllenInstitute/bmtk.git

requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - six
    - numpy
    - pandas
    - matplotlib
    - jsonschema
    - h5py
    - lxml

test:
  imports:
    - bmtk

about:
  home: https://github.com/AllenInstitute/bmtk
  license: BSD
  license_file: LICENSE.txt